export const MOCK_POSTS = [
  {
    id: 1,
    title: "직장 내 AI가 가져올 업무 효율성의 미래",
    description: "IMR의 일상적인 워크플로우와 생산성을 LLM이 어떻게 변화시키고 있는지 탐구합니다. 우리는 단순히 도구를 사용하는 것을 넘어, 기계와 협업하는 새로운 패러다임을 맞이하고 있습니다.",
    category: "TECH",
    author: "Alex Rivera",
    date: "MAR 27, 2026",
    size: "lg" as const,
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: 2,
    title: "새로운 오피스 라운지: 오픈 안내",
    description: "3층 라운지가 모던 매거진 콘셉트로 리뉴얼되었습니다. 여백의 미와 기하학적 엄격함이 돋보이는 공간에서 영감을 얻으세요. 지금 방문해보세요!",
    category: "NOTICE",
    author: "Admin",
    date: "MAR 26, 2026",
    size: "md" as const,
  },
  {
    id: 3,
    title: "아이디어 제안: 주간 테크 티타임",
    description: "매주 금요일 오후에 모여 새로운 기술 트렌드에 대해 논의하고 인사이트를 공유하는 자리를 제안합니다.",
    category: "IDEA",
    author: "Jordan Smith",
    date: "MAR 25, 2026",
    size: "sm" as const,
  },
  {
    id: 4,
    title: "제주도 주말 여행: 포토 덤프",
    description: "지난 주말 제주도 워크샵 여행에서 담아온 영감 넘치는 아름다운 순간들을 공유합니다.",
    category: "LOUNGE",
    author: "Sarah Chen",
    date: "MAR 24, 2026",
    size: "sm" as const,
    thumbnail: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: 5,
    title: "대규모 데이터를 위한 Prisma 쿼리 최적화",
    description: "IMR의 백엔드 성능 향상을 위한 SQLite 튜닝, 인덱싱 전략 및 N+1 문제 해결에 대한 심층 분석 가이드.",
    category: "TECH",
    author: "Mike Johnson",
    date: "MAR 23, 2026",
    size: "md" as const,
  },
]
